### ISSUE TITLE
Author,Please add mysql supported

### ISSUE THREAD

**Issue by xiaonian233** [riskawarrior/Mjolnir-Authentication-Server#3]
Author,Please add mysql supported.

**Comment by xiaonian233** [comment]
Author,I hava trouble in your patcher

**Comment by rutkai** [comment]
Hey, what's up?
Please start a separate ticket for the feature request and the troubleshooting (and please provide as much information as possible like: logs, behaviour, etc. for the troubleshooting ticket).
Thanks!

**Comment by xiaonian233** [comment]
![image](https://user-images.githubusercontent.com/21072615/43684755-94a288e4-98d8-11e8-9ecd-c8ad38d2d519.png)

**Comment by xiaonian233** [comment]
I directly modified authlib, replace some string to use this project,but when i multiplay,I just saw my skin,I think may be public key's problem,so i used your patcher
