### ISSUE TITLE
OpenSSL not found

### ISSUE THREAD

**Issue by DariusSG** [riskawarrior/Mjolnir-Authentication-Server#4]
When starting it throws an error that OpenSSL is not found on these paths 
.../lib/pem/openssl.js
.../lib/which.js
.../lib/isexe/index.js
.../lib/isexe/which.js
Pls help

**Comment by DariusSG** [comment]
Using windows 10

**Comment by DariusSG** [comment]
Solved it but now it says that it cannot find the server(launcher)

**Comment by ABSanthosh** [comment]
@DariusSG Please post how you fixed it for others as well.
