### ISSUE TITLE
does this have to be a valid Mojang account

### ISSUE THREAD

**Issue by qwertyqop** [riskawarrior/Mjolnir-Authentication-Server#7]
Does the accounts that are added to Mjolnir have to be valid accounts. Because I cannot login even though everything seems to be working fine. I get no errors on the app.js.

**Comment by rutkai** [comment]
Hey,

No, the accounts doesn't have to be valid on the live servers. You have to patch both the server and client jars, then register a user account within Mjolnir.

See more in the [Usage](https://github.com/rutkai/Mjolnir-Authentication-Server/blob/master/docs/Usage.md) and [Installation guide](https://github.com/rutkai/Mjolnir-Authentication-Server/blob/master/docs/Installation.md) pages.
