### ISSUE TITLE
Is this a good idea to change Host File in client ?

### ISSUE THREAD

**Issue by evanlegamer** [riskawarrior/Mjolnir-Authentication-Server#9]
Hi, i want to use your mjolnir authenthification system, but i'm not sure that modifiing the host file of the client is good idea, could you tell me more about that, how it actually work and if it's not so problematic to do so. Thank you in advance for your help.

**Comment by rutkai** [comment]
Hey,

Hosts file modification is the easiest way to redirect the traffic which is going to the destination server (which is hosted by Microsoft by default). Another option could be a custom DNS server but it's harder to set up.

Please note though that it was  long time ago when Mjolnir got an update so it may not work anymore.
